### ISSUE TITLE
Totalul, in anexe, este afisat cu prea multe zecimale

### ISSUE THREAD

**Issue by DarianTUDOR** [UptProjectRaven/ProjectRaven#52]
![image](https://user-images.githubusercontent.com/52955915/69409602-ef61f180-0d11-11ea-96b6-5c565904b808.png)

**Comment by DarianTUDOR** [comment]
![image](https://user-images.githubusercontent.com/52955915/69412379-6bab0380-0d17-11ea-936c-5c9b56f6ec27.png)

validare pentru valori pozitive

**Comment by SeOcSa** [comment]
Will be fixed by: https://github.com/UptProjectRaven/ProjectRaven/issues/100
